# Required to make the "experiments" dir the default one for the output of the models
hydra:
  job:
    chdir: true
  run:
    dir: ./experiments/${model.model_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - run: train
  - model: depth_double_mobilenet
  - data: faceforensicsplusplus_c40_depth

project: 'depthfake' 