# reproducibility
seed: 42

cuda_device: '0'

# pl_trainer
pl_trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: 'gpu'
  devices: [0]
  max_epochs: 1
  

experiment:
  checkpoint_file: weights_2/rgb_mobilenet/2023-04-10/23-13-19/experiments/accuracy/rgb_mobilenet/epoch=16-step=10829.ckpt

  check_all: False
  checkpoint_file_acc: weights_2/depth_mask_mobilenet/2023-04-11/15-07-22/experiments/accuracy/depth_mask_mobilenet/epoch=28-step=18270.ckpt
  checkpoint_file_loss: weights_2/depth_mask_mobilenet/2023-04-11/15-07-22/experiments/loss/depth_mask_mobilenet/epoch=2-step=1890.ckpt
  checkpoint_file_last: weights_2/depth_mask_mobilenet/2023-04-11/15-07-22/experiments/last/depth_mask_mobilenet


####################################################################################################
## #                               Checkpoint                                      #     Model    ##
## #'experiments/rgb/2022-10-21/00-31-20/experiments/rgb/epoch=20-step=30114.ckpt' #  resnet50    ##
## #'experiments/rgb/2022-10-21/04-02-19/experiments/rgb/epoch=8-step=12906.ckpt ' # mobilenet_v2 ##
## #'experiments/rgb/2022-10-21/04-02-19/experiments/rgb/epoch=8-step=12906.ckpt ' # mobilenet_v2 ##