# reproducibility
seed: 42

cuda_device: '0'

# pl_trainer
pl_trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: 'gpu'
  devices: [0]
  max_epochs: 1
  

experiment:
  checkpoint_file: /media/weights_2/c40/deepfakes/depth_mask_mobilenet/2023-04-11/11-02-04/experiments/accuracy/depth_mask_mobilenet/epoch=29-step=18900.ckpt

  check_all: False
  checkpoint_file_acc: /media/weights_2/raw/deepfakes/depth_xception/2023-05-05/16-37-45/experiments/accuracy/depth_xception/epoch=21-step=13948.ckpt
  checkpoint_file_loss: /media/weights_2/raw/deepfakes/depth_xception/2023-05-05/16-37-45/experiments/loss/depth_xception/epoch=0-step=634.ckpt
  checkpoint_file_last: /media/weights_2/raw/deepfakes/depth_xception/2023-05-05/16-37-45/experiments/last/depth_xception


####################################################################################################
## #                               Checkpoint                                      #     Model    ##
## #'experiments/rgb/2022-10-21/00-31-20/experiments/rgb/epoch=20-step=30114.ckpt' #  resnet50    ##
## #'experiments/rgb/2022-10-21/04-02-19/experiments/rgb/epoch=8-step=12906.ckpt ' # mobilenet_v2 ##
## #'experiments/rgb/2022-10-21/04-02-19/experiments/rgb/epoch=8-step=12906.ckpt ' # mobilenet_v2 ##