# reproducibility
seed: 42

# pl_trainer
pl_trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: 'gpu'
  devices: [6]
  max_epochs: 1
  

experiment:
  checkpoint_file: experiments/rgb/2022-10-21/06-28-55/experiments/rgb/epoch=11-step=17208.ckpt


####################################################################################################
## #                               Checkpoint                                      #     Model    ##
## #'experiments/rgb/2022-10-21/00-31-20/experiments/rgb/epoch=20-step=30114.ckpt' #  resnet50    ##
## #'experiments/rgb/2022-10-21/04-02-19/experiments/rgb/epoch=8-step=12906.ckpt ' # mobilenet_v2 ##
## #'experiments/rgb/2022-10-21/04-02-19/experiments/rgb/epoch=8-step=12906.ckpt ' # mobilenet_v2 ##